import express from 'express';
import { uploadSingleImage } from '../middleware/upload.js';
import { requireAuth } from '../middleware/auth.js';

const router = express.Router();

// POST /api/uploads/images
// Accepts a single image file field named "image" (multipart/form-data)
// Returns: { url: string, originalName: string, size: number, mimeType: string }
router.post('/images', requireAuth, (req, res) => {
  uploadSingleImage(req, res, (err) => {
    if (err) {
      if (err.message === 'Only image uploads are allowed') {
        return res.status(400).json({ error: err.message });
      }
      if (err.code === 'LIMIT_FILE_SIZE') {
        return res.status(413).json({ error: 'Image too large (max 5MB)' });
      }
      console.error('Image upload error:', err);
      return res.status(500).json({ error: 'Failed to upload image' });
    }

    if (!req.file) {
      return res.status(400).json({ error: 'No image file provided' });
    }

    // Public URL under /uploads; filename is generated by multer
    const publicUrl = `/uploads/${req.file.filename}`;

    return res.status(201).json({
      url: publicUrl,
      originalName: req.file.originalname,
      size: req.file.size,
      mimeType: req.file.mimetype,
    });
  });
});

export default router;

